# Use postgres/example user/password credentials
version: "3.1"

services:
  student-dashboard:
    build: ../backend
    ports:
      - "80:80"
    depends_on:
      - "db"

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: students
      POSTGRES_USER: nklisch
      POSTGRES_DB: cs314_dashboard
    volumes:
      - /home/nathan/pgdata:/var/lib/postgresql/data
